# SonarQube Project Configuration
sonar.projectDescription=Altas-Catalog Connector for Jenkins
sonar.projectKey=acamposm_atlas-jenkins-connector
sonar.projectName=Atlas Jenkins Connector
sonar.projectVersion=0.1.0

# Path to source directories
sonar.sources=src
sonar.tests=tests

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Language
sonar.language=php

# Test execution and coverage reports
sonar.php.phpunit.reportPaths=build/junit.xml
sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.phpstan.reportPaths=build/phpstan-report.xml

# Exclusions
sonar.exclusions=vendor/**, build/**, .phpunit.cache/**
